project:
  type: website
  output-dir: docs
  
website:
  title: "Quantitative Methods for Historians - HIKU8863"
  
  navbar:
    type: inverse
    right:
    - text: "Overview"
      icon: fa-home
      href: index.qmd
    - text: "Instructions"
      icon: fa-list-ul
      href: instructions.qmd
    - text: "Intro to R"
      icon: fa-book
      href: get-r.qmd      
    - text: "Case-studies"
      icon: fa-book
      menu: 
      - text: "The Paisley Prisoners"
        href: backg-paisley.qmd
      - text: "The State of the Union Speeches"
        href: backg-speeches.qmd
      - text: "The Tudor Network of Letters"
        href: backg-tnp.qmd  
    - text: "Coursework"
      href: coursework.qmd
    - text: "Other sources"
      href: other-data.qmd
    - text: "Further readings"
      href: further-readings.qmd  
  sidebar:
    title: "Contents"
    style: "docked"
    # pinned: true
    # collapse-level: 3
    contents:
      - text: "Contents"
        file: index.qmd
      - section: "1. Descriptive Statistics"
        contents: 
          - text: "1.1. Qualitative variables"
            #file: r-scripts/desc_qual.qmd
          - text: "1.2. Numerical variables" 
          - text: "1.3. Bivariate statistics" 
          - text: "1.4. Textual information" 
          - text: "1.5. Mapping" 
          - text: "1.6. Social networks" 
      - text: "2. Correlation and regression"
      - text: "3. Uncertainty"
      - section: "4. Regression analysis"
        contents: 
          - text: "4.1. Multiple regression"
          - text: "4.2. Challenges to regression" 
      - text: "5. From sources to data"
bibliography: refs.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-cap-location: margin
    fig-align: center
    linkcolor: $blue
