project:
  type: website
  output-dir: docs
  
website:
  title: "Quantitative Methods for Historians - HIKU8863"
  
  navbar:
    type: inverse
    
    right:
    - text: "Overview"
      icon: fa-home
      href: index.qmd
    - text: "Instructions"
      icon: fa-list-ul
      href: instructions.qmd
    - text: "Intro to R"
      icon: fa-book
      href: get-r.qmd      
    - text: "Case-studies"
      icon: fa-book
      menu: 
      - text: "The Paisley Prisoners"
        href: backg-paisley.qmd
      - text: "The State of the Union Speeches"
        href: backg-speeches.qmd
      #- text: "The Tudor Network of Letters"
       # href: backg-tnp.qmd  
    - text: "Coursework"
      href: coursework.qmd
      
  sidebar:
    title: "Contents"
    style: "docked"
    # pinned: true
    # collapse-level: 3
    contents:
      - text: "Contents"
        file: index.qmd
      - section: "1. From sources to data"
        contents: 
          - text: "1.1. Transcribing sources"
          - text: "1.2. What is data?"
          - text: "1.3. Cleaning / Re-categorisation"   
      - section: "2. Descriptive Statistics"
        contents: 
          - text: "2.1. Qualitative variables"
            #file: r-scripts/desc_qual.qmd
          - text: "2.2. Numerical variables" 
          - text: "2.3. Bivariate statistics" 
          - text: "2.4. Textual information" 
          - text: "2.5. Mapping" 
          # - text: "1.6. Social networks" 
      - text: "3. Uncertainty"
      - text: "4. Correlation and regression"
      - section: "5. Regression analysis"
        contents: 
          - text: "5.1. Multiple regression"
          - text: "5.2. Challenges to regression" 
      - text: "---" # to create extra space
      - section: "Additional material"
        contents:
          - text: "Other sources"
            file: other-data.qmd
          - text: "Further readings"
            file: further-readings.qmd  
            
bibliography: refs.bib

format:
  html:
    page-layout: full
    grid:
      margin-width: 420px
    theme: cosmo
    css: styles.css
    toc: true
    fig-cap: false
    fig-number: false
    #fig-align: center  
    linkcolor: $blue