---
title: "Further reading"
---

For additional background on quantification in history, check the texts below: 

- Graham, Shawn, Milligan, Ian, Weingart, Scott and Martin, Kim (2022), [The joys of big data for historians](readings/graham-etal2022.pdf), in *Exploring Big Historical Data. The Historians Macroscope* (World Scientific; 2nd Edition), pp. 1-34.

- Fourie, Johan (2023), [Quantitative history and uncharted people](readings/fourie2023.pdf), in *Quantitative history and uncharted people. Case studies from the South African Past* (Bloomsbury), pp. 1-32.

- Lemercier, Claire and Zalc, Claire (2021), [Back to the sources. Practicing and teaching quantitative history in the 2020s](readings/lemercier-zalc-2021.pdf), *Capitalism. A Journal of History and Economics*, vol. 2, no. 2, pp. 473-508.

- Blaxill, Luke (2023), [Why do historians ignore digital analysis. Bring on the Luddites](readings/blaxill2023.pdf), *The Political Quarterly*, vol. 94, no. 2, pp. 279-289.

- Jockers, Matthew L. (2013), [Macroanalysis. Foundation](readings/jockers2013.pdf), in *Macroanalysis. Digital Methods and Literary History* (University of Illinois Press), pp. 3-32.

---

For discussions on the use of computational methods in the humanities in general, see:

- Kirschenbaum, Matthew (2010), [What is Digital Humanities and what's it doing in English departments?](https://mkirschenbaum.wordpress.com/wp-content/uploads/2011/03/ade-final.pdf), *ADE Bulletin* 50.

- Fish, Stanley (2012), [Mind Your P’s and B’s: The Digital Humanities and Interpretation](https://archive.nytimes.com/opinionator.blogs.nytimes.com/2012/01/23/mind-your-ps-and-bs-the-digital-humanities-and-interpretation/), *The New York Times* (Jan 23, 2012).

- Marche, Stephen (2012), [Literature is not data](https://lareviewofbooks.org/article/literature-is-not-data-against-digital-humanities/), *Los Angeles Review of Books* (Oct 28, 2012).

- Kirschenbaum, Matthew (2014), [What is “Digital Humanities,” and why are they saying such terrible things about it?](https://mkirschenbaum.wordpress.com/wp-content/uploads/2014/04/dhterriblethingskirschenbaum.pdf), *Differences* 25 (1).
https://mkirschenbaum.wordpress.com/wp-content/uploads/2011/03/ade-final.pdf

- Posner, Miriam (2015), [Humanities Data: A Necessary Contradiction](https://miriamposner.com/blog/humanities-data-a-necessary-contradiction/), Blogpost.

---

See also the following blogposts discussing the pros and cons of using AI in history, especially for historians engaging with digital methods, a subject that is continuously evolving:

- Humphries, Mark: [Is this the last generation of historians?](https://generativehistory.substack.com/p/is-this-the-last-generation-of-historians) (Feb 7, 2025).

- Humphries, Mark: [Steering a middle course on AI in the history classroom](https://generativehistory.substack.com/p/steering-a-middle-course-on-ai-in) (June 13, 2025).

- Cohen, Dan: [The Writing Is on the Wall for Handwriting Recognition](https://newsletter.dancohen.org/archive/the-writing-is-on-the-wall-for-handwriting-recognition) (Nov 25, 2025)

- Blevins, Cameron: [Generative AI and History in 2025](https://cblevins.github.io/posts/gen-ai-history-2025/) (Dec 19, 2025)

- Mullen, Lincoln: [Behind, ahead](https://lincolnmullen.com/blog/behind-ahead/) (March 9, 2026).

- Blevins, Cameron: [Bottlenecks, side quests and the calculus of historical research](https://cblevins.github.io/posts/bottleneck-side-quests/) (March 27, 2026).

- Humphries, Mark: [The agents and waking up](https://generativehistory.substack.com/p/the-agents-are-waking-up) (April 17, 2026).

- Regan, Amanda: [Teaching computational history in the age of AI](https://amanda-regan.com/posts/teaching-computational-history-age-of-ai/) (August 5, 2026).
